run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  goheader:
    template-path: header.txt
  goimports:
    local-prefixes: github.com/signalfx/splunk-otel-collector-operator
  maligned:
    suggest-new: true
  misspell:
    locale: US
  # TODO: please enable in beta stage once we know all configuration fields
  # govet:
  #  enable:
  #    - fieldalignment

linters:
  enable:
    - goheader
    - goimports
    - misspell
    - gosec
    - exhaustive
    - godot
    - unparam